### ISSUE TITLE
[BUG] Проблема с блоками.

### ISSUE THREAD

**Issue by sannelo** [SuperAnt30/Mvk#1]
Если поставить блок на максимальной высоте (256), там где блоки уже не могут ставиться, то блок из инвентаря пропадет, так как будто он поставился. [Гифка](https://i.imgur.com/VSIUtob.gif)

**Comment by SuperAnt30** [comment]
Спасибо! Поправлю, там на 0 и 255 высоте прорисовка ещё кривая. Тоже поправлю.

**Comment by SuperAnt30** [comment]
Fix 0.0.9.0
